builds:
  - id: cli
    main: "."
    ldflags:
      - -X github.com/keyval-dev/odigos/cli/cmd.OdigosVersion={{ .Env.VERSION }}
      - -X github.com/keyval-dev/odigos/cli/cmd.OdigosCommit={{ .Env.SHORT_COMMIT }}
      - -X github.com/keyval-dev/odigos/cli/cmd.OdigosDate={{ .Env.DATE }}
