apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-server
  name: grpc-server
  namespace: odigos-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      shareProcessNamespace: true
      initContainers:
        - name: odigos-init
          image: edenfed/init:v0.1
          imagePullPolicy: IfNotPresent
          command:
            - cp
            - -a
            - /odigos-init/.
            - /odigos/
          volumeMounts:
            - name: odigos
              mountPath: /odigos
      containers:
        - image: edenfed/grpc-server:v0.1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          name: grpc-server
          ports:
            - containerPort: 50051
              protocol: TCP
          command:
            - /odigos/init
            - /workspace/app
          volumeMounts:
            - name: odigos
              mountPath: /odigos
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        - name: grpc-instrumentation
          image: keyval/otel-go-agent:v0.6.0
          env:
            - name: OTEL_TARGET_EXE
              value: /workspace/app
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "jaeger:4317"
            - name: OTEL_SERVICE_NAME
              value: "hello-grpc"
          securityContext:
            runAsUser: 0
            capabilities:
              add:
                - SYS_PTRACE
            privileged: true
          volumeMounts:
            - mountPath: /sys/kernel/debug
              name: kernel-debug
      volumes:
        - name: odigos
          emptyDir: {}
        - name: kernel-debug
          hostPath:
            path: /sys/kernel/debug
