dist:
  module: github.com/keyval-dev/odigos/odigoscol
  name: odigoscol
  description: Odigos OpenTelemetry Collector.
  version: 0.0.1
  otelcol_version: 0.87.0

extensions:

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.87.0
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.87.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.87.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awss3exporter v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/azuredataexplorerexporter v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/azuremonitorexporter v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudpubsubexporter v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlemanagedprometheusexporter v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/dynatraceexporter v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/logzioexporter v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/lokiexporter v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/sentryexporter v0.87.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunkhecexporter v0.87.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.87.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.87.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.87.0

connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.87.0

replaces:
