apiVersion: odigos.io/v1alpha1
kind: Destination
metadata:
  generateName: odigos.io.dest.jaeger-
  namespace: odigos-system
spec:
  data:
    JAEGER_URL: test-opentelemetry-collector.traces:4317
  destinationName: collector
  signals:
    - TRACES
  type: jaeger