name: build

on:
  pull_request:
    branches:
      - main

jobs:
  build-autoscaler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Autoscaler Image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: autoscaler:pr-${{ github.event.number }}
          build-args: SERVICE_NAME=autoscaler
  build-scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Scheduler Image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: scheduler:pr-${{ github.event.number }}
          build-args: SERVICE_NAME=scheduler
  build-and-test-instrumentor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.0"
      - name: Build Instrumentor Image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: instrumentor:pr-${{ github.event.number }}
          build-args: SERVICE_NAME=instrumentor
      - name: run tests
        working-directory: ./instrumentor
        run: |
          make test

  build-odiglet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Odiglet Image
        uses: docker/build-push-action@v5
        with:
          file: odiglet/Dockerfile
          context: .
          push: false
          tags: odiglet:pr-${{ github.event.number }}
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Frontend Image
        uses: docker/build-push-action@v5
        with:
          file: frontend/Dockerfile
          context: .
          push: false
          tags: frontend:pr-${{ github.event.number }}

  test-common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.0"
      - name: Test common module
        working-directory: ./common
        run: |
          go test -v ./...

  test-procdiscovery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.0"
      - name: Test procdiscovery module
        working-directory: ./procdiscovery
        run: |
          go test -v ./...