name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  packages: write
jobs:
  release:
    runs-on:
      labels: large-runner
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Set env
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Autoscaler Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/keyval-dev/odigos/autoscaler:${{ steps.vars.outputs.tag }}
            keyval/odigos-autoscaler:${{ steps.vars.outputs.tag }}
          build-args: SERVICE_NAME=autoscaler
          platforms: linux/amd64,linux/arm64
      - name: Build Scheduler Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/keyval-dev/odigos/scheduler:${{ steps.vars.outputs.tag }}
            keyval/odigos-scheduler:${{ steps.vars.outputs.tag }}
          build-args: SERVICE_NAME=scheduler
          platforms: linux/amd64,linux/arm64
      - name: Build Instrumentor Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/keyval-dev/odigos/instrumentor:${{ steps.vars.outputs.tag }}
            keyval/odigos-instrumentor:${{ steps.vars.outputs.tag }}
          build-args: SERVICE_NAME=instrumentor
          platforms: linux/amd64,linux/arm64
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build Odiglet Image
        uses: docker/build-push-action@v5
        with:
          file: odiglet/Dockerfile
          push: true
          tags: |
            ghcr.io/keyval-dev/odigos/odiglet:${{ steps.vars.outputs.tag }}
            keyval/odigos-odiglet:${{ steps.vars.outputs.tag }}
          platforms: linux/amd64,linux/arm64
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
      - name: Get changelog and set to an env variable
        run: |
          echo "CHANGELOG=$(git log $(git describe --tags --abbrev=0 @^)..@ --format='- <https://github.com/keyval-dev/odigos/commit/%H|%h>: %s \n')" >> $GITHUB_ENV
      - name: Send new release announcement to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'CHANNEL_ID' # TODO: Set channel ID
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New Odligos release: ${{  github.ref_name }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://github.com/keyval-dev/odigos/releases/tag/${{  github.ref_name }}|Release ${{  github.ref_name }}> is out"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Changelog: \n $CHANGELOG"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ODIGOS_SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK