name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Set env
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.2'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Autoscaler Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/keyval-dev/odigos/autoscaler:${{ steps.vars.outputs.tag }}
            keyval/odigos-autoscaler:${{ steps.vars.outputs.tag }}
          build-args: SERVICE_NAME=autoscaler
          platforms: linux/amd64,linux/arm64
      - name: Build Scheduler Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/keyval-dev/odigos/scheduler:${{ steps.vars.outputs.tag }}
            keyval/odigos-scheduler:${{ steps.vars.outputs.tag }}
          build-args: SERVICE_NAME=scheduler
          platforms: linux/amd64,linux/arm64
      - name: Build Instrumentor Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/keyval-dev/odigos/instrumentor:${{ steps.vars.outputs.tag }}
            keyval/odigos-instrumentor:${{ steps.vars.outputs.tag }}
          build-args: SERVICE_NAME=instrumentor
          platforms: linux/amd64,linux/arm64
      - name: Build Odiglet Image
        uses: docker/build-push-action@v4
        with:
          file: odiglet/Dockerfile
          push: true
          tags: |
            ghcr.io/keyval-dev/odigos/odiglet:${{ steps.vars.outputs.tag }}
            keyval/odigos-odiglet:${{ steps.vars.outputs.tag }}
          platforms: linux/amd64,linux/arm64
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}