name: Publish Modules

on:
  push:
    tags:
      - "v*"

jobs:
  tag-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Extract Tag
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: tag api
        run: |
          git tag api/${{ steps.extract_tag.outputs.tag }}

      - name: tag common
        run: |
          git tag common/${{ steps.extract_tag.outputs.tag }}

      - name: tag odiglet
        run: |
          git tag odiglet/${{ steps.extract_tag.outputs.tag }}

      - name: Push Module Tags
        run: |
          git push origin --tags

      - name: Trigger a workflow in another repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.RELEASE_BOT_TOKEN }}" \
            https://api.github.com/repos/keyval-dev/odigos-enterprise/dispatches \
            -d '{"event_type": "create_release_pr", "client_payload": {"tag": "${{ steps.extract_tag.outputs.tag }}"}}'

  publish-docker-images:
    runs-on: large-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract Tag
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Autoscaler Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            keyval/odigos-autoscaler:${{ steps.extract_tag.outputs.tag }}
          build-args: SERVICE_NAME=autoscaler
          platforms: linux/amd64,linux/arm64

      - name: Build Scheduler Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            keyval/odigos-scheduler:${{ steps.extract_tag.outputs.tag }}
          build-args: SERVICE_NAME=scheduler
          platforms: linux/amd64,linux/arm64

      - name: Build Instrumentor Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            keyval/odigos-instrumentor:${{ steps.extract_tag.outputs.tag }}
          build-args: SERVICE_NAME=instrumentor
          platforms: linux/amd64,linux/arm64

      - name: Build Odiglet Image
        uses: docker/build-push-action@v5
        with:
          file: odiglet/Dockerfile
          push: true
          tags: |
            keyval/odigos-odiglet:${{ steps.extract_tag.outputs.tag }}
          platforms: linux/amd64,linux/arm64
