name: Publish Odiglet Base Builder

on:
  push:
    branches:
      - main
    paths:
      - "odiglet/base.Dockerfile"

permissions:
  contents: write
  packages: write

env:
  DOCKERHUB_ORG: "keyval"

jobs:
  publish-odiglet-base-builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Publish Odiglet Base Builder
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./odiglet/base.Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_ORG }}/odiglet-base:latest
