name: Publish Odiglet Base Builder

on:
  workflow_dispatch: 
    inputs:
      image_tag:
        description: 'The new image tag for the base builder docker image (e.g. v1.0)'
        required: true

permissions:
  contents: write
  packages: write

env:
  DOCKERHUB_ORG: "keyval"

jobs:
  publish-odiglet-base-builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Validate New Version
        run: |
          # Fetch tags from Docker Hub (modify this according to your specific needs)
          TAGS=$(curl -s "https://hub.docker.com/v2/repositories/${{ env.DOCKERHUB_ORG }}/odiglet-base/tags/" | jq -r '.results[].name')
  
          # The new version from workflow input
          NEW_VERSION=${{ github.event.inputs.image_tag }}
  
          # Function to compare versions
          function version_gt() { 
            test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1"; 
          }
  
          # Loop through the tags and compare
          for TAG in $TAGS; do
            if version_gt "$TAG" "$NEW_VERSION"; then
              echo "Error: New version $NEW_VERSION is older than existing version $TAG"
              exit 1
            fi
          done    - name: Validate New Version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Publish Odiglet Base Builder
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./odiglet/base.Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_ORG }}/odiglet-base:${{ github.event.inputs.image_tag }}
