name: Verify Odiglet Base Builder

# This workflow is designed to verify the Odiglet Base Builder Dockerfile on pull requests.
# It builds the Dockerfile without pushing it, ensuring that it's valid and can successfully create an image.

on:
  pull_request:
    paths:
      - "odiglet/base.Dockerfile"

jobs:
  verify-odiglet-base-builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./odiglet/base.Dockerfile
          push: false
