name: Publish Odiglet Base Builder

on:
  pull_request:
    paths:
      - "odiglet/base.Dockerfile"

jobs:
  publish-odiglet-base-builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Publish Odiglet Base Builder
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./odiglet/base.Dockerfile
          push: false
